//go:build !ignore_autogenerated_conversions
// +build !ignore_autogenerated_conversions

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen-v0.29.0. DO NOT EDIT.

package v1beta1

import (
	unsafe "unsafe"

	apiv1beta1 "github.com/k3s-io/cluster-api-k3s/bootstrap/api/v1beta1"
	apiv1beta2 "github.com/k3s-io/cluster-api-k3s/bootstrap/api/v1beta2"
	v1beta2 "github.com/k3s-io/cluster-api-k3s/controlplane/api/v1beta2"
	errors "github.com/k3s-io/cluster-api-k3s/pkg/errors"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	clusterapiapiv1beta1 "sigs.k8s.io/cluster-api/api/v1beta1"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*KThreesControlPlane)(nil), (*v1beta2.KThreesControlPlane)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_KThreesControlPlane_To_v1beta2_KThreesControlPlane(a.(*KThreesControlPlane), b.(*v1beta2.KThreesControlPlane), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.KThreesControlPlane)(nil), (*KThreesControlPlane)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_KThreesControlPlane_To_v1beta1_KThreesControlPlane(a.(*v1beta2.KThreesControlPlane), b.(*KThreesControlPlane), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KThreesControlPlaneList)(nil), (*v1beta2.KThreesControlPlaneList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_KThreesControlPlaneList_To_v1beta2_KThreesControlPlaneList(a.(*KThreesControlPlaneList), b.(*v1beta2.KThreesControlPlaneList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.KThreesControlPlaneList)(nil), (*KThreesControlPlaneList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_KThreesControlPlaneList_To_v1beta1_KThreesControlPlaneList(a.(*v1beta2.KThreesControlPlaneList), b.(*KThreesControlPlaneList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KThreesControlPlaneMachineTemplate)(nil), (*v1beta2.KThreesControlPlaneMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_KThreesControlPlaneMachineTemplate_To_v1beta2_KThreesControlPlaneMachineTemplate(a.(*KThreesControlPlaneMachineTemplate), b.(*v1beta2.KThreesControlPlaneMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KThreesControlPlaneStatus)(nil), (*v1beta2.KThreesControlPlaneStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_KThreesControlPlaneStatus_To_v1beta2_KThreesControlPlaneStatus(a.(*KThreesControlPlaneStatus), b.(*v1beta2.KThreesControlPlaneStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LastRemediationStatus)(nil), (*v1beta2.LastRemediationStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_LastRemediationStatus_To_v1beta2_LastRemediationStatus(a.(*LastRemediationStatus), b.(*v1beta2.LastRemediationStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.LastRemediationStatus)(nil), (*LastRemediationStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_LastRemediationStatus_To_v1beta1_LastRemediationStatus(a.(*v1beta2.LastRemediationStatus), b.(*LastRemediationStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RemediationStrategy)(nil), (*v1beta2.RemediationStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RemediationStrategy_To_v1beta2_RemediationStrategy(a.(*RemediationStrategy), b.(*v1beta2.RemediationStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.RemediationStrategy)(nil), (*RemediationStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_RemediationStrategy_To_v1beta1_RemediationStrategy(a.(*v1beta2.RemediationStrategy), b.(*RemediationStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*apiv1beta1.KThreesConfigSpec)(nil), (*apiv1beta2.KThreesConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_KThreesConfigSpec_To_v1beta2_KThreesConfigSpec(a.(*apiv1beta1.KThreesConfigSpec), b.(*apiv1beta2.KThreesConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*KThreesControlPlaneSpec)(nil), (*v1beta2.KThreesControlPlaneSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_KThreesControlPlaneSpec_To_v1beta2_KThreesControlPlaneSpec(a.(*KThreesControlPlaneSpec), b.(*v1beta2.KThreesControlPlaneSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*apiv1beta2.KThreesConfigSpec)(nil), (*apiv1beta1.KThreesConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_KThreesConfigSpec_To_v1beta1_KThreesConfigSpec(a.(*apiv1beta2.KThreesConfigSpec), b.(*apiv1beta1.KThreesConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.KThreesControlPlaneMachineTemplate)(nil), (*KThreesControlPlaneMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_KThreesControlPlaneMachineTemplate_To_v1beta1_KThreesControlPlaneMachineTemplate(a.(*v1beta2.KThreesControlPlaneMachineTemplate), b.(*KThreesControlPlaneMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.KThreesControlPlaneSpec)(nil), (*KThreesControlPlaneSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_KThreesControlPlaneSpec_To_v1beta1_KThreesControlPlaneSpec(a.(*v1beta2.KThreesControlPlaneSpec), b.(*KThreesControlPlaneSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.KThreesControlPlaneStatus)(nil), (*KThreesControlPlaneStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_KThreesControlPlaneStatus_To_v1beta1_KThreesControlPlaneStatus(a.(*v1beta2.KThreesControlPlaneStatus), b.(*KThreesControlPlaneStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_KThreesControlPlane_To_v1beta2_KThreesControlPlane(in *KThreesControlPlane, out *v1beta2.KThreesControlPlane, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_KThreesControlPlaneSpec_To_v1beta2_KThreesControlPlaneSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_KThreesControlPlaneStatus_To_v1beta2_KThreesControlPlaneStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_KThreesControlPlane_To_v1beta2_KThreesControlPlane is an autogenerated conversion function.
func Convert_v1beta1_KThreesControlPlane_To_v1beta2_KThreesControlPlane(in *KThreesControlPlane, out *v1beta2.KThreesControlPlane, s conversion.Scope) error {
	return autoConvert_v1beta1_KThreesControlPlane_To_v1beta2_KThreesControlPlane(in, out, s)
}

func autoConvert_v1beta2_KThreesControlPlane_To_v1beta1_KThreesControlPlane(in *v1beta2.KThreesControlPlane, out *KThreesControlPlane, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta2_KThreesControlPlaneSpec_To_v1beta1_KThreesControlPlaneSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_KThreesControlPlaneStatus_To_v1beta1_KThreesControlPlaneStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_KThreesControlPlane_To_v1beta1_KThreesControlPlane is an autogenerated conversion function.
func Convert_v1beta2_KThreesControlPlane_To_v1beta1_KThreesControlPlane(in *v1beta2.KThreesControlPlane, out *KThreesControlPlane, s conversion.Scope) error {
	return autoConvert_v1beta2_KThreesControlPlane_To_v1beta1_KThreesControlPlane(in, out, s)
}

func autoConvert_v1beta1_KThreesControlPlaneList_To_v1beta2_KThreesControlPlaneList(in *KThreesControlPlaneList, out *v1beta2.KThreesControlPlaneList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta2.KThreesControlPlane, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_KThreesControlPlane_To_v1beta2_KThreesControlPlane(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_KThreesControlPlaneList_To_v1beta2_KThreesControlPlaneList is an autogenerated conversion function.
func Convert_v1beta1_KThreesControlPlaneList_To_v1beta2_KThreesControlPlaneList(in *KThreesControlPlaneList, out *v1beta2.KThreesControlPlaneList, s conversion.Scope) error {
	return autoConvert_v1beta1_KThreesControlPlaneList_To_v1beta2_KThreesControlPlaneList(in, out, s)
}

func autoConvert_v1beta2_KThreesControlPlaneList_To_v1beta1_KThreesControlPlaneList(in *v1beta2.KThreesControlPlaneList, out *KThreesControlPlaneList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KThreesControlPlane, len(*in))
		for i := range *in {
			if err := Convert_v1beta2_KThreesControlPlane_To_v1beta1_KThreesControlPlane(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta2_KThreesControlPlaneList_To_v1beta1_KThreesControlPlaneList is an autogenerated conversion function.
func Convert_v1beta2_KThreesControlPlaneList_To_v1beta1_KThreesControlPlaneList(in *v1beta2.KThreesControlPlaneList, out *KThreesControlPlaneList, s conversion.Scope) error {
	return autoConvert_v1beta2_KThreesControlPlaneList_To_v1beta1_KThreesControlPlaneList(in, out, s)
}

func autoConvert_v1beta1_KThreesControlPlaneMachineTemplate_To_v1beta2_KThreesControlPlaneMachineTemplate(in *KThreesControlPlaneMachineTemplate, out *v1beta2.KThreesControlPlaneMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	return nil
}

// Convert_v1beta1_KThreesControlPlaneMachineTemplate_To_v1beta2_KThreesControlPlaneMachineTemplate is an autogenerated conversion function.
func Convert_v1beta1_KThreesControlPlaneMachineTemplate_To_v1beta2_KThreesControlPlaneMachineTemplate(in *KThreesControlPlaneMachineTemplate, out *v1beta2.KThreesControlPlaneMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1beta1_KThreesControlPlaneMachineTemplate_To_v1beta2_KThreesControlPlaneMachineTemplate(in, out, s)
}

func autoConvert_v1beta2_KThreesControlPlaneMachineTemplate_To_v1beta1_KThreesControlPlaneMachineTemplate(in *v1beta2.KThreesControlPlaneMachineTemplate, out *KThreesControlPlaneMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	// WARNING: in.InfrastructureRef requires manual conversion: does not exist in peer-type
	// WARNING: in.NodeDrainTimeout requires manual conversion: does not exist in peer-type
	// WARNING: in.NodeVolumeDetachTimeout requires manual conversion: does not exist in peer-type
	// WARNING: in.NodeDeletionTimeout requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1beta1_KThreesControlPlaneSpec_To_v1beta2_KThreesControlPlaneSpec(in *KThreesControlPlaneSpec, out *v1beta2.KThreesControlPlaneSpec, s conversion.Scope) error {
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.Version = in.Version
	// WARNING: in.InfrastructureTemplate requires manual conversion: does not exist in peer-type
	if err := Convert_v1beta1_KThreesConfigSpec_To_v1beta2_KThreesConfigSpec(&in.KThreesConfigSpec, &out.KThreesConfigSpec, s); err != nil {
		return err
	}
	// WARNING: in.UpgradeAfter requires manual conversion: does not exist in peer-type
	// WARNING: in.NodeDrainTimeout requires manual conversion: does not exist in peer-type
	if err := Convert_v1beta1_KThreesControlPlaneMachineTemplate_To_v1beta2_KThreesControlPlaneMachineTemplate(&in.MachineTemplate, &out.MachineTemplate, s); err != nil {
		return err
	}
	out.RemediationStrategy = (*v1beta2.RemediationStrategy)(unsafe.Pointer(in.RemediationStrategy))
	return nil
}

func autoConvert_v1beta2_KThreesControlPlaneSpec_To_v1beta1_KThreesControlPlaneSpec(in *v1beta2.KThreesControlPlaneSpec, out *KThreesControlPlaneSpec, s conversion.Scope) error {
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.Version = in.Version
	if err := Convert_v1beta2_KThreesConfigSpec_To_v1beta1_KThreesConfigSpec(&in.KThreesConfigSpec, &out.KThreesConfigSpec, s); err != nil {
		return err
	}
	// WARNING: in.RolloutAfter requires manual conversion: does not exist in peer-type
	if err := Convert_v1beta2_KThreesControlPlaneMachineTemplate_To_v1beta1_KThreesControlPlaneMachineTemplate(&in.MachineTemplate, &out.MachineTemplate, s); err != nil {
		return err
	}
	out.RemediationStrategy = (*RemediationStrategy)(unsafe.Pointer(in.RemediationStrategy))
	return nil
}

func autoConvert_v1beta1_KThreesControlPlaneStatus_To_v1beta2_KThreesControlPlaneStatus(in *KThreesControlPlaneStatus, out *v1beta2.KThreesControlPlaneStatus, s conversion.Scope) error {
	out.Selector = in.Selector
	out.Replicas = in.Replicas
	out.UpdatedReplicas = in.UpdatedReplicas
	out.ReadyReplicas = in.ReadyReplicas
	out.UnavailableReplicas = in.UnavailableReplicas
	out.Initialized = in.Initialized
	out.Ready = in.Ready
	out.FailureReason = errors.KThreesControlPlaneStatusError(in.FailureReason)
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.ObservedGeneration = in.ObservedGeneration
	out.Conditions = *(*clusterapiapiv1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	out.LastRemediation = (*v1beta2.LastRemediationStatus)(unsafe.Pointer(in.LastRemediation))
	return nil
}

// Convert_v1beta1_KThreesControlPlaneStatus_To_v1beta2_KThreesControlPlaneStatus is an autogenerated conversion function.
func Convert_v1beta1_KThreesControlPlaneStatus_To_v1beta2_KThreesControlPlaneStatus(in *KThreesControlPlaneStatus, out *v1beta2.KThreesControlPlaneStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_KThreesControlPlaneStatus_To_v1beta2_KThreesControlPlaneStatus(in, out, s)
}

func autoConvert_v1beta2_KThreesControlPlaneStatus_To_v1beta1_KThreesControlPlaneStatus(in *v1beta2.KThreesControlPlaneStatus, out *KThreesControlPlaneStatus, s conversion.Scope) error {
	out.Selector = in.Selector
	out.Replicas = in.Replicas
	// WARNING: in.Version requires manual conversion: does not exist in peer-type
	out.UpdatedReplicas = in.UpdatedReplicas
	out.ReadyReplicas = in.ReadyReplicas
	out.UnavailableReplicas = in.UnavailableReplicas
	out.Initialized = in.Initialized
	out.Ready = in.Ready
	out.FailureReason = errors.KThreesControlPlaneStatusError(in.FailureReason)
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.ObservedGeneration = in.ObservedGeneration
	out.Conditions = *(*clusterapiapiv1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	out.LastRemediation = (*LastRemediationStatus)(unsafe.Pointer(in.LastRemediation))
	return nil
}

func autoConvert_v1beta1_LastRemediationStatus_To_v1beta2_LastRemediationStatus(in *LastRemediationStatus, out *v1beta2.LastRemediationStatus, s conversion.Scope) error {
	out.Machine = in.Machine
	out.Timestamp = in.Timestamp
	out.RetryCount = in.RetryCount
	return nil
}

// Convert_v1beta1_LastRemediationStatus_To_v1beta2_LastRemediationStatus is an autogenerated conversion function.
func Convert_v1beta1_LastRemediationStatus_To_v1beta2_LastRemediationStatus(in *LastRemediationStatus, out *v1beta2.LastRemediationStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_LastRemediationStatus_To_v1beta2_LastRemediationStatus(in, out, s)
}

func autoConvert_v1beta2_LastRemediationStatus_To_v1beta1_LastRemediationStatus(in *v1beta2.LastRemediationStatus, out *LastRemediationStatus, s conversion.Scope) error {
	out.Machine = in.Machine
	out.Timestamp = in.Timestamp
	out.RetryCount = in.RetryCount
	return nil
}

// Convert_v1beta2_LastRemediationStatus_To_v1beta1_LastRemediationStatus is an autogenerated conversion function.
func Convert_v1beta2_LastRemediationStatus_To_v1beta1_LastRemediationStatus(in *v1beta2.LastRemediationStatus, out *LastRemediationStatus, s conversion.Scope) error {
	return autoConvert_v1beta2_LastRemediationStatus_To_v1beta1_LastRemediationStatus(in, out, s)
}

func autoConvert_v1beta1_RemediationStrategy_To_v1beta2_RemediationStrategy(in *RemediationStrategy, out *v1beta2.RemediationStrategy, s conversion.Scope) error {
	out.MaxRetry = (*int32)(unsafe.Pointer(in.MaxRetry))
	out.RetryPeriod = in.RetryPeriod
	out.MinHealthyPeriod = (*v1.Duration)(unsafe.Pointer(in.MinHealthyPeriod))
	return nil
}

// Convert_v1beta1_RemediationStrategy_To_v1beta2_RemediationStrategy is an autogenerated conversion function.
func Convert_v1beta1_RemediationStrategy_To_v1beta2_RemediationStrategy(in *RemediationStrategy, out *v1beta2.RemediationStrategy, s conversion.Scope) error {
	return autoConvert_v1beta1_RemediationStrategy_To_v1beta2_RemediationStrategy(in, out, s)
}

func autoConvert_v1beta2_RemediationStrategy_To_v1beta1_RemediationStrategy(in *v1beta2.RemediationStrategy, out *RemediationStrategy, s conversion.Scope) error {
	out.MaxRetry = (*int32)(unsafe.Pointer(in.MaxRetry))
	out.RetryPeriod = in.RetryPeriod
	out.MinHealthyPeriod = (*v1.Duration)(unsafe.Pointer(in.MinHealthyPeriod))
	return nil
}

// Convert_v1beta2_RemediationStrategy_To_v1beta1_RemediationStrategy is an autogenerated conversion function.
func Convert_v1beta2_RemediationStrategy_To_v1beta1_RemediationStrategy(in *v1beta2.RemediationStrategy, out *RemediationStrategy, s conversion.Scope) error {
	return autoConvert_v1beta2_RemediationStrategy_To_v1beta1_RemediationStrategy(in, out, s)
}
