//go:build !ignore_autogenerated_conversions
// +build !ignore_autogenerated_conversions

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen-v0.29.0. DO NOT EDIT.

package v1beta1

import (
	unsafe "unsafe"

	v1beta2 "github.com/k3s-io/cluster-api-k3s/bootstrap/api/v1beta2"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	apiv1beta1 "sigs.k8s.io/cluster-api/api/v1beta1"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*File)(nil), (*v1beta2.File)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_File_To_v1beta2_File(a.(*File), b.(*v1beta2.File), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.File)(nil), (*File)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_File_To_v1beta1_File(a.(*v1beta2.File), b.(*File), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FileSource)(nil), (*v1beta2.FileSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_FileSource_To_v1beta2_FileSource(a.(*FileSource), b.(*v1beta2.FileSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.FileSource)(nil), (*FileSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_FileSource_To_v1beta1_FileSource(a.(*v1beta2.FileSource), b.(*FileSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KThreesAgentConfig)(nil), (*v1beta2.KThreesAgentConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_KThreesAgentConfig_To_v1beta2_KThreesAgentConfig(a.(*KThreesAgentConfig), b.(*v1beta2.KThreesAgentConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.KThreesAgentConfig)(nil), (*KThreesAgentConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_KThreesAgentConfig_To_v1beta1_KThreesAgentConfig(a.(*v1beta2.KThreesAgentConfig), b.(*KThreesAgentConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KThreesConfig)(nil), (*v1beta2.KThreesConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_KThreesConfig_To_v1beta2_KThreesConfig(a.(*KThreesConfig), b.(*v1beta2.KThreesConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.KThreesConfig)(nil), (*KThreesConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_KThreesConfig_To_v1beta1_KThreesConfig(a.(*v1beta2.KThreesConfig), b.(*KThreesConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KThreesConfigList)(nil), (*v1beta2.KThreesConfigList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_KThreesConfigList_To_v1beta2_KThreesConfigList(a.(*KThreesConfigList), b.(*v1beta2.KThreesConfigList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.KThreesConfigList)(nil), (*KThreesConfigList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_KThreesConfigList_To_v1beta1_KThreesConfigList(a.(*v1beta2.KThreesConfigList), b.(*KThreesConfigList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KThreesConfigSpec)(nil), (*v1beta2.KThreesConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_KThreesConfigSpec_To_v1beta2_KThreesConfigSpec(a.(*KThreesConfigSpec), b.(*v1beta2.KThreesConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.KThreesConfigSpec)(nil), (*KThreesConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_KThreesConfigSpec_To_v1beta1_KThreesConfigSpec(a.(*v1beta2.KThreesConfigSpec), b.(*KThreesConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KThreesConfigStatus)(nil), (*v1beta2.KThreesConfigStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_KThreesConfigStatus_To_v1beta2_KThreesConfigStatus(a.(*KThreesConfigStatus), b.(*v1beta2.KThreesConfigStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.KThreesConfigStatus)(nil), (*KThreesConfigStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_KThreesConfigStatus_To_v1beta1_KThreesConfigStatus(a.(*v1beta2.KThreesConfigStatus), b.(*KThreesConfigStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KThreesConfigTemplate)(nil), (*v1beta2.KThreesConfigTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_KThreesConfigTemplate_To_v1beta2_KThreesConfigTemplate(a.(*KThreesConfigTemplate), b.(*v1beta2.KThreesConfigTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.KThreesConfigTemplate)(nil), (*KThreesConfigTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_KThreesConfigTemplate_To_v1beta1_KThreesConfigTemplate(a.(*v1beta2.KThreesConfigTemplate), b.(*KThreesConfigTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KThreesConfigTemplateList)(nil), (*v1beta2.KThreesConfigTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_KThreesConfigTemplateList_To_v1beta2_KThreesConfigTemplateList(a.(*KThreesConfigTemplateList), b.(*v1beta2.KThreesConfigTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.KThreesConfigTemplateList)(nil), (*KThreesConfigTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_KThreesConfigTemplateList_To_v1beta1_KThreesConfigTemplateList(a.(*v1beta2.KThreesConfigTemplateList), b.(*KThreesConfigTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KThreesConfigTemplateResource)(nil), (*v1beta2.KThreesConfigTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_KThreesConfigTemplateResource_To_v1beta2_KThreesConfigTemplateResource(a.(*KThreesConfigTemplateResource), b.(*v1beta2.KThreesConfigTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.KThreesConfigTemplateResource)(nil), (*KThreesConfigTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_KThreesConfigTemplateResource_To_v1beta1_KThreesConfigTemplateResource(a.(*v1beta2.KThreesConfigTemplateResource), b.(*KThreesConfigTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KThreesConfigTemplateSpec)(nil), (*v1beta2.KThreesConfigTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_KThreesConfigTemplateSpec_To_v1beta2_KThreesConfigTemplateSpec(a.(*KThreesConfigTemplateSpec), b.(*v1beta2.KThreesConfigTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.KThreesConfigTemplateSpec)(nil), (*KThreesConfigTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_KThreesConfigTemplateSpec_To_v1beta1_KThreesConfigTemplateSpec(a.(*v1beta2.KThreesConfigTemplateSpec), b.(*KThreesConfigTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SecretFileSource)(nil), (*v1beta2.SecretFileSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SecretFileSource_To_v1beta2_SecretFileSource(a.(*SecretFileSource), b.(*v1beta2.SecretFileSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.SecretFileSource)(nil), (*SecretFileSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_SecretFileSource_To_v1beta1_SecretFileSource(a.(*v1beta2.SecretFileSource), b.(*SecretFileSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*KThreesServerConfig)(nil), (*v1beta2.KThreesServerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_KThreesServerConfig_To_v1beta2_KThreesServerConfig(a.(*KThreesServerConfig), b.(*v1beta2.KThreesServerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.KThreesServerConfig)(nil), (*KThreesServerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_KThreesServerConfig_To_v1beta1_KThreesServerConfig(a.(*v1beta2.KThreesServerConfig), b.(*KThreesServerConfig), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_File_To_v1beta2_File(in *File, out *v1beta2.File, s conversion.Scope) error {
	out.Path = in.Path
	out.Owner = in.Owner
	out.Permissions = in.Permissions
	out.Encoding = v1beta2.Encoding(in.Encoding)
	out.Content = in.Content
	out.ContentFrom = (*v1beta2.FileSource)(unsafe.Pointer(in.ContentFrom))
	return nil
}

// Convert_v1beta1_File_To_v1beta2_File is an autogenerated conversion function.
func Convert_v1beta1_File_To_v1beta2_File(in *File, out *v1beta2.File, s conversion.Scope) error {
	return autoConvert_v1beta1_File_To_v1beta2_File(in, out, s)
}

func autoConvert_v1beta2_File_To_v1beta1_File(in *v1beta2.File, out *File, s conversion.Scope) error {
	out.Path = in.Path
	out.Owner = in.Owner
	out.Permissions = in.Permissions
	out.Encoding = Encoding(in.Encoding)
	out.Content = in.Content
	out.ContentFrom = (*FileSource)(unsafe.Pointer(in.ContentFrom))
	return nil
}

// Convert_v1beta2_File_To_v1beta1_File is an autogenerated conversion function.
func Convert_v1beta2_File_To_v1beta1_File(in *v1beta2.File, out *File, s conversion.Scope) error {
	return autoConvert_v1beta2_File_To_v1beta1_File(in, out, s)
}

func autoConvert_v1beta1_FileSource_To_v1beta2_FileSource(in *FileSource, out *v1beta2.FileSource, s conversion.Scope) error {
	if err := Convert_v1beta1_SecretFileSource_To_v1beta2_SecretFileSource(&in.Secret, &out.Secret, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_FileSource_To_v1beta2_FileSource is an autogenerated conversion function.
func Convert_v1beta1_FileSource_To_v1beta2_FileSource(in *FileSource, out *v1beta2.FileSource, s conversion.Scope) error {
	return autoConvert_v1beta1_FileSource_To_v1beta2_FileSource(in, out, s)
}

func autoConvert_v1beta2_FileSource_To_v1beta1_FileSource(in *v1beta2.FileSource, out *FileSource, s conversion.Scope) error {
	if err := Convert_v1beta2_SecretFileSource_To_v1beta1_SecretFileSource(&in.Secret, &out.Secret, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_FileSource_To_v1beta1_FileSource is an autogenerated conversion function.
func Convert_v1beta2_FileSource_To_v1beta1_FileSource(in *v1beta2.FileSource, out *FileSource, s conversion.Scope) error {
	return autoConvert_v1beta2_FileSource_To_v1beta1_FileSource(in, out, s)
}

func autoConvert_v1beta1_KThreesAgentConfig_To_v1beta2_KThreesAgentConfig(in *KThreesAgentConfig, out *v1beta2.KThreesAgentConfig, s conversion.Scope) error {
	out.NodeLabels = *(*[]string)(unsafe.Pointer(&in.NodeLabels))
	out.NodeTaints = *(*[]string)(unsafe.Pointer(&in.NodeTaints))
	out.PrivateRegistry = in.PrivateRegistry
	out.KubeletArgs = *(*[]string)(unsafe.Pointer(&in.KubeletArgs))
	out.KubeProxyArgs = *(*[]string)(unsafe.Pointer(&in.KubeProxyArgs))
	out.NodeName = in.NodeName
	out.AirGapped = in.AirGapped
	return nil
}

// Convert_v1beta1_KThreesAgentConfig_To_v1beta2_KThreesAgentConfig is an autogenerated conversion function.
func Convert_v1beta1_KThreesAgentConfig_To_v1beta2_KThreesAgentConfig(in *KThreesAgentConfig, out *v1beta2.KThreesAgentConfig, s conversion.Scope) error {
	return autoConvert_v1beta1_KThreesAgentConfig_To_v1beta2_KThreesAgentConfig(in, out, s)
}

func autoConvert_v1beta2_KThreesAgentConfig_To_v1beta1_KThreesAgentConfig(in *v1beta2.KThreesAgentConfig, out *KThreesAgentConfig, s conversion.Scope) error {
	out.NodeLabels = *(*[]string)(unsafe.Pointer(&in.NodeLabels))
	out.NodeTaints = *(*[]string)(unsafe.Pointer(&in.NodeTaints))
	out.PrivateRegistry = in.PrivateRegistry
	out.KubeletArgs = *(*[]string)(unsafe.Pointer(&in.KubeletArgs))
	out.KubeProxyArgs = *(*[]string)(unsafe.Pointer(&in.KubeProxyArgs))
	out.NodeName = in.NodeName
	out.AirGapped = in.AirGapped
	return nil
}

// Convert_v1beta2_KThreesAgentConfig_To_v1beta1_KThreesAgentConfig is an autogenerated conversion function.
func Convert_v1beta2_KThreesAgentConfig_To_v1beta1_KThreesAgentConfig(in *v1beta2.KThreesAgentConfig, out *KThreesAgentConfig, s conversion.Scope) error {
	return autoConvert_v1beta2_KThreesAgentConfig_To_v1beta1_KThreesAgentConfig(in, out, s)
}

func autoConvert_v1beta1_KThreesConfig_To_v1beta2_KThreesConfig(in *KThreesConfig, out *v1beta2.KThreesConfig, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_KThreesConfigSpec_To_v1beta2_KThreesConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_KThreesConfigStatus_To_v1beta2_KThreesConfigStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_KThreesConfig_To_v1beta2_KThreesConfig is an autogenerated conversion function.
func Convert_v1beta1_KThreesConfig_To_v1beta2_KThreesConfig(in *KThreesConfig, out *v1beta2.KThreesConfig, s conversion.Scope) error {
	return autoConvert_v1beta1_KThreesConfig_To_v1beta2_KThreesConfig(in, out, s)
}

func autoConvert_v1beta2_KThreesConfig_To_v1beta1_KThreesConfig(in *v1beta2.KThreesConfig, out *KThreesConfig, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta2_KThreesConfigSpec_To_v1beta1_KThreesConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_KThreesConfigStatus_To_v1beta1_KThreesConfigStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_KThreesConfig_To_v1beta1_KThreesConfig is an autogenerated conversion function.
func Convert_v1beta2_KThreesConfig_To_v1beta1_KThreesConfig(in *v1beta2.KThreesConfig, out *KThreesConfig, s conversion.Scope) error {
	return autoConvert_v1beta2_KThreesConfig_To_v1beta1_KThreesConfig(in, out, s)
}

func autoConvert_v1beta1_KThreesConfigList_To_v1beta2_KThreesConfigList(in *KThreesConfigList, out *v1beta2.KThreesConfigList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta2.KThreesConfig, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_KThreesConfig_To_v1beta2_KThreesConfig(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_KThreesConfigList_To_v1beta2_KThreesConfigList is an autogenerated conversion function.
func Convert_v1beta1_KThreesConfigList_To_v1beta2_KThreesConfigList(in *KThreesConfigList, out *v1beta2.KThreesConfigList, s conversion.Scope) error {
	return autoConvert_v1beta1_KThreesConfigList_To_v1beta2_KThreesConfigList(in, out, s)
}

func autoConvert_v1beta2_KThreesConfigList_To_v1beta1_KThreesConfigList(in *v1beta2.KThreesConfigList, out *KThreesConfigList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KThreesConfig, len(*in))
		for i := range *in {
			if err := Convert_v1beta2_KThreesConfig_To_v1beta1_KThreesConfig(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta2_KThreesConfigList_To_v1beta1_KThreesConfigList is an autogenerated conversion function.
func Convert_v1beta2_KThreesConfigList_To_v1beta1_KThreesConfigList(in *v1beta2.KThreesConfigList, out *KThreesConfigList, s conversion.Scope) error {
	return autoConvert_v1beta2_KThreesConfigList_To_v1beta1_KThreesConfigList(in, out, s)
}

func autoConvert_v1beta1_KThreesConfigSpec_To_v1beta2_KThreesConfigSpec(in *KThreesConfigSpec, out *v1beta2.KThreesConfigSpec, s conversion.Scope) error {
	out.Files = *(*[]v1beta2.File)(unsafe.Pointer(&in.Files))
	out.PreK3sCommands = *(*[]string)(unsafe.Pointer(&in.PreK3sCommands))
	out.PostK3sCommands = *(*[]string)(unsafe.Pointer(&in.PostK3sCommands))
	if err := Convert_v1beta1_KThreesAgentConfig_To_v1beta2_KThreesAgentConfig(&in.AgentConfig, &out.AgentConfig, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_KThreesServerConfig_To_v1beta2_KThreesServerConfig(&in.ServerConfig, &out.ServerConfig, s); err != nil {
		return err
	}
	out.Version = in.Version
	return nil
}

// Convert_v1beta1_KThreesConfigSpec_To_v1beta2_KThreesConfigSpec is an autogenerated conversion function.
func Convert_v1beta1_KThreesConfigSpec_To_v1beta2_KThreesConfigSpec(in *KThreesConfigSpec, out *v1beta2.KThreesConfigSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_KThreesConfigSpec_To_v1beta2_KThreesConfigSpec(in, out, s)
}

func autoConvert_v1beta2_KThreesConfigSpec_To_v1beta1_KThreesConfigSpec(in *v1beta2.KThreesConfigSpec, out *KThreesConfigSpec, s conversion.Scope) error {
	out.Files = *(*[]File)(unsafe.Pointer(&in.Files))
	out.PreK3sCommands = *(*[]string)(unsafe.Pointer(&in.PreK3sCommands))
	out.PostK3sCommands = *(*[]string)(unsafe.Pointer(&in.PostK3sCommands))
	if err := Convert_v1beta2_KThreesAgentConfig_To_v1beta1_KThreesAgentConfig(&in.AgentConfig, &out.AgentConfig, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_KThreesServerConfig_To_v1beta1_KThreesServerConfig(&in.ServerConfig, &out.ServerConfig, s); err != nil {
		return err
	}
	out.Version = in.Version
	return nil
}

// Convert_v1beta2_KThreesConfigSpec_To_v1beta1_KThreesConfigSpec is an autogenerated conversion function.
func Convert_v1beta2_KThreesConfigSpec_To_v1beta1_KThreesConfigSpec(in *v1beta2.KThreesConfigSpec, out *KThreesConfigSpec, s conversion.Scope) error {
	return autoConvert_v1beta2_KThreesConfigSpec_To_v1beta1_KThreesConfigSpec(in, out, s)
}

func autoConvert_v1beta1_KThreesConfigStatus_To_v1beta2_KThreesConfigStatus(in *KThreesConfigStatus, out *v1beta2.KThreesConfigStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.BootstrapData = *(*[]byte)(unsafe.Pointer(&in.BootstrapData))
	out.DataSecretName = (*string)(unsafe.Pointer(in.DataSecretName))
	out.FailureReason = in.FailureReason
	out.FailureMessage = in.FailureMessage
	out.ObservedGeneration = in.ObservedGeneration
	out.Conditions = *(*apiv1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1beta1_KThreesConfigStatus_To_v1beta2_KThreesConfigStatus is an autogenerated conversion function.
func Convert_v1beta1_KThreesConfigStatus_To_v1beta2_KThreesConfigStatus(in *KThreesConfigStatus, out *v1beta2.KThreesConfigStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_KThreesConfigStatus_To_v1beta2_KThreesConfigStatus(in, out, s)
}

func autoConvert_v1beta2_KThreesConfigStatus_To_v1beta1_KThreesConfigStatus(in *v1beta2.KThreesConfigStatus, out *KThreesConfigStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.BootstrapData = *(*[]byte)(unsafe.Pointer(&in.BootstrapData))
	out.DataSecretName = (*string)(unsafe.Pointer(in.DataSecretName))
	out.FailureReason = in.FailureReason
	out.FailureMessage = in.FailureMessage
	out.ObservedGeneration = in.ObservedGeneration
	out.Conditions = *(*apiv1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1beta2_KThreesConfigStatus_To_v1beta1_KThreesConfigStatus is an autogenerated conversion function.
func Convert_v1beta2_KThreesConfigStatus_To_v1beta1_KThreesConfigStatus(in *v1beta2.KThreesConfigStatus, out *KThreesConfigStatus, s conversion.Scope) error {
	return autoConvert_v1beta2_KThreesConfigStatus_To_v1beta1_KThreesConfigStatus(in, out, s)
}

func autoConvert_v1beta1_KThreesConfigTemplate_To_v1beta2_KThreesConfigTemplate(in *KThreesConfigTemplate, out *v1beta2.KThreesConfigTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_KThreesConfigTemplateSpec_To_v1beta2_KThreesConfigTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_KThreesConfigTemplate_To_v1beta2_KThreesConfigTemplate is an autogenerated conversion function.
func Convert_v1beta1_KThreesConfigTemplate_To_v1beta2_KThreesConfigTemplate(in *KThreesConfigTemplate, out *v1beta2.KThreesConfigTemplate, s conversion.Scope) error {
	return autoConvert_v1beta1_KThreesConfigTemplate_To_v1beta2_KThreesConfigTemplate(in, out, s)
}

func autoConvert_v1beta2_KThreesConfigTemplate_To_v1beta1_KThreesConfigTemplate(in *v1beta2.KThreesConfigTemplate, out *KThreesConfigTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta2_KThreesConfigTemplateSpec_To_v1beta1_KThreesConfigTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_KThreesConfigTemplate_To_v1beta1_KThreesConfigTemplate is an autogenerated conversion function.
func Convert_v1beta2_KThreesConfigTemplate_To_v1beta1_KThreesConfigTemplate(in *v1beta2.KThreesConfigTemplate, out *KThreesConfigTemplate, s conversion.Scope) error {
	return autoConvert_v1beta2_KThreesConfigTemplate_To_v1beta1_KThreesConfigTemplate(in, out, s)
}

func autoConvert_v1beta1_KThreesConfigTemplateList_To_v1beta2_KThreesConfigTemplateList(in *KThreesConfigTemplateList, out *v1beta2.KThreesConfigTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta2.KThreesConfigTemplate, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_KThreesConfigTemplate_To_v1beta2_KThreesConfigTemplate(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_KThreesConfigTemplateList_To_v1beta2_KThreesConfigTemplateList is an autogenerated conversion function.
func Convert_v1beta1_KThreesConfigTemplateList_To_v1beta2_KThreesConfigTemplateList(in *KThreesConfigTemplateList, out *v1beta2.KThreesConfigTemplateList, s conversion.Scope) error {
	return autoConvert_v1beta1_KThreesConfigTemplateList_To_v1beta2_KThreesConfigTemplateList(in, out, s)
}

func autoConvert_v1beta2_KThreesConfigTemplateList_To_v1beta1_KThreesConfigTemplateList(in *v1beta2.KThreesConfigTemplateList, out *KThreesConfigTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KThreesConfigTemplate, len(*in))
		for i := range *in {
			if err := Convert_v1beta2_KThreesConfigTemplate_To_v1beta1_KThreesConfigTemplate(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta2_KThreesConfigTemplateList_To_v1beta1_KThreesConfigTemplateList is an autogenerated conversion function.
func Convert_v1beta2_KThreesConfigTemplateList_To_v1beta1_KThreesConfigTemplateList(in *v1beta2.KThreesConfigTemplateList, out *KThreesConfigTemplateList, s conversion.Scope) error {
	return autoConvert_v1beta2_KThreesConfigTemplateList_To_v1beta1_KThreesConfigTemplateList(in, out, s)
}

func autoConvert_v1beta1_KThreesConfigTemplateResource_To_v1beta2_KThreesConfigTemplateResource(in *KThreesConfigTemplateResource, out *v1beta2.KThreesConfigTemplateResource, s conversion.Scope) error {
	if err := Convert_v1beta1_KThreesConfigSpec_To_v1beta2_KThreesConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_KThreesConfigTemplateResource_To_v1beta2_KThreesConfigTemplateResource is an autogenerated conversion function.
func Convert_v1beta1_KThreesConfigTemplateResource_To_v1beta2_KThreesConfigTemplateResource(in *KThreesConfigTemplateResource, out *v1beta2.KThreesConfigTemplateResource, s conversion.Scope) error {
	return autoConvert_v1beta1_KThreesConfigTemplateResource_To_v1beta2_KThreesConfigTemplateResource(in, out, s)
}

func autoConvert_v1beta2_KThreesConfigTemplateResource_To_v1beta1_KThreesConfigTemplateResource(in *v1beta2.KThreesConfigTemplateResource, out *KThreesConfigTemplateResource, s conversion.Scope) error {
	if err := Convert_v1beta2_KThreesConfigSpec_To_v1beta1_KThreesConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_KThreesConfigTemplateResource_To_v1beta1_KThreesConfigTemplateResource is an autogenerated conversion function.
func Convert_v1beta2_KThreesConfigTemplateResource_To_v1beta1_KThreesConfigTemplateResource(in *v1beta2.KThreesConfigTemplateResource, out *KThreesConfigTemplateResource, s conversion.Scope) error {
	return autoConvert_v1beta2_KThreesConfigTemplateResource_To_v1beta1_KThreesConfigTemplateResource(in, out, s)
}

func autoConvert_v1beta1_KThreesConfigTemplateSpec_To_v1beta2_KThreesConfigTemplateSpec(in *KThreesConfigTemplateSpec, out *v1beta2.KThreesConfigTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1beta1_KThreesConfigTemplateResource_To_v1beta2_KThreesConfigTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_KThreesConfigTemplateSpec_To_v1beta2_KThreesConfigTemplateSpec is an autogenerated conversion function.
func Convert_v1beta1_KThreesConfigTemplateSpec_To_v1beta2_KThreesConfigTemplateSpec(in *KThreesConfigTemplateSpec, out *v1beta2.KThreesConfigTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_KThreesConfigTemplateSpec_To_v1beta2_KThreesConfigTemplateSpec(in, out, s)
}

func autoConvert_v1beta2_KThreesConfigTemplateSpec_To_v1beta1_KThreesConfigTemplateSpec(in *v1beta2.KThreesConfigTemplateSpec, out *KThreesConfigTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1beta2_KThreesConfigTemplateResource_To_v1beta1_KThreesConfigTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_KThreesConfigTemplateSpec_To_v1beta1_KThreesConfigTemplateSpec is an autogenerated conversion function.
func Convert_v1beta2_KThreesConfigTemplateSpec_To_v1beta1_KThreesConfigTemplateSpec(in *v1beta2.KThreesConfigTemplateSpec, out *KThreesConfigTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1beta2_KThreesConfigTemplateSpec_To_v1beta1_KThreesConfigTemplateSpec(in, out, s)
}

func autoConvert_v1beta1_KThreesServerConfig_To_v1beta2_KThreesServerConfig(in *KThreesServerConfig, out *v1beta2.KThreesServerConfig, s conversion.Scope) error {
	out.KubeAPIServerArgs = *(*[]string)(unsafe.Pointer(&in.KubeAPIServerArgs))
	out.KubeControllerManagerArgs = *(*[]string)(unsafe.Pointer(&in.KubeControllerManagerArgs))
	out.KubeSchedulerArgs = *(*[]string)(unsafe.Pointer(&in.KubeSchedulerArgs))
	out.TLSSan = *(*[]string)(unsafe.Pointer(&in.TLSSan))
	out.BindAddress = in.BindAddress
	out.HTTPSListenPort = in.HTTPSListenPort
	out.AdvertiseAddress = in.AdvertiseAddress
	out.AdvertisePort = in.AdvertisePort
	out.ClusterCidr = in.ClusterCidr
	out.ServiceCidr = in.ServiceCidr
	out.ClusterDNS = in.ClusterDNS
	out.ClusterDomain = in.ClusterDomain
	out.DisableComponents = *(*[]string)(unsafe.Pointer(&in.DisableComponents))
	// WARNING: in.DisableExternalCloudProvider requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1beta2_KThreesServerConfig_To_v1beta1_KThreesServerConfig(in *v1beta2.KThreesServerConfig, out *KThreesServerConfig, s conversion.Scope) error {
	out.KubeAPIServerArgs = *(*[]string)(unsafe.Pointer(&in.KubeAPIServerArgs))
	out.KubeControllerManagerArgs = *(*[]string)(unsafe.Pointer(&in.KubeControllerManagerArgs))
	out.KubeSchedulerArgs = *(*[]string)(unsafe.Pointer(&in.KubeSchedulerArgs))
	out.TLSSan = *(*[]string)(unsafe.Pointer(&in.TLSSan))
	out.BindAddress = in.BindAddress
	out.HTTPSListenPort = in.HTTPSListenPort
	out.AdvertiseAddress = in.AdvertiseAddress
	out.AdvertisePort = in.AdvertisePort
	out.ClusterCidr = in.ClusterCidr
	out.ServiceCidr = in.ServiceCidr
	out.ClusterDNS = in.ClusterDNS
	out.ClusterDomain = in.ClusterDomain
	out.DisableComponents = *(*[]string)(unsafe.Pointer(&in.DisableComponents))
	// WARNING: in.DeprecatedDisableExternalCloudProvider requires manual conversion: does not exist in peer-type
	// WARNING: in.DisableCloudController requires manual conversion: does not exist in peer-type
	// WARNING: in.CloudProviderName requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1beta1_SecretFileSource_To_v1beta2_SecretFileSource(in *SecretFileSource, out *v1beta2.SecretFileSource, s conversion.Scope) error {
	out.Name = in.Name
	out.Key = in.Key
	return nil
}

// Convert_v1beta1_SecretFileSource_To_v1beta2_SecretFileSource is an autogenerated conversion function.
func Convert_v1beta1_SecretFileSource_To_v1beta2_SecretFileSource(in *SecretFileSource, out *v1beta2.SecretFileSource, s conversion.Scope) error {
	return autoConvert_v1beta1_SecretFileSource_To_v1beta2_SecretFileSource(in, out, s)
}

func autoConvert_v1beta2_SecretFileSource_To_v1beta1_SecretFileSource(in *v1beta2.SecretFileSource, out *SecretFileSource, s conversion.Scope) error {
	out.Name = in.Name
	out.Key = in.Key
	return nil
}

// Convert_v1beta2_SecretFileSource_To_v1beta1_SecretFileSource is an autogenerated conversion function.
func Convert_v1beta2_SecretFileSource_To_v1beta1_SecretFileSource(in *v1beta2.SecretFileSource, out *SecretFileSource, s conversion.Scope) error {
	return autoConvert_v1beta2_SecretFileSource_To_v1beta1_SecretFileSource(in, out, s)
}
