name: E2E tests (PR Blocker)
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions: {}

jobs:
  e2e-tests:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    timeout-minutes: 60
    steps:
      - name: 'Clear out GitHub Runner'
        run: |
          echo "Space Before:"
          df -h / --total | grep total | awk '{print $4}'

          PATHS_TO_REMOVE=(
            "/usr/lib/jvm"
            "/usr/share/dotnet"
            "/usr/share/swift"
            "/usr/local/.ghcup"
            "/usr/local/julia*"
            "/usr/local/lib/android"
            "/usr/local/share/chromium"
            "/opt/microsoft"
            "/opt/google"
            "/opt/az"
            "/usr/local/share/powershell"
            "/opt/hostedtoolcache"
          )
          for path in "${PATHS_TO_REMOVE[@]}"; do
            sudo rm -rf "$path"
          done
          docker system prune -af
          docker builder prune -af
          docker image prune -af
          docker volume prune -af

          echo "Space After:"
          df -h / --total | grep total | awk '{print $4}'
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2 https://github.com/actions/checkout/tags
      - name: Install Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0 https://github.com/actions/setup-go/tags
        with:
          go-version-file: go.mod
          cache: true
      - name: Build e2e image
        run: make docker-build-e2e
      - name: Install kind
        run: go install sigs.k8s.io/kind@c5f516c8b2c4927232074381c980467e393cf965 # v0.26.0 https://github.com/kubernetes-sigs/kind/tags
      - name: Run E2E tests
        run: make GINKGO_FOCUS="\\[PR-Blocking\\]" test-e2e
      - name: Archive artifacts
        if: always()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0 https://github.com/actions/upload-artifact/tags
        with:
          name: e2e-artifacts
          path: _artifacts
          if-no-files-found: ignore
