name: Pull Request Validation
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  validate:
    name: "Validate ${{ matrix.target }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: ["lint", "test-bootstrap", "test-controlplane", "test-common"]

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: ${{ matrix.target }}
        run: make ${{ matrix.target }}

      - name: check there are no changes after re-generation
        run: test -z "$(git status --porcelain)" || (echo 'Changes detected after running make build'; git status; git --no-pager diff; false)
