name: Pull Request Validation
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    name: "Validate ${{ matrix.target }}"
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        target: ["lint", "test-bootstrap", "test-controlplane", "test-common"]

    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6.0.2 https://github.com/actions/checkout/tags

      - name: Install Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v6.4.0 https://github.com/actions/setup-go/tags
        with:
          go-version-file: go.mod
          cache: true

      - name: ${{ matrix.target }}
        run: make ${{ matrix.target }}

      - name: check there are no changes after re-generation
        run: test -z "$(git status --porcelain)" || (echo 'Changes detected after running make build'; git status; git --no-pager diff; false)
